import {
  FaCode,
  FaBootstrap,
  FaIcons,
  FaDesktop,
  FaInfinity,
  FaMobileAlt,
  FaJs,
  FaHeadset,
  FaSyncAlt,
  FaTerminal,
  FaReact,
  FaSearch,
  FaLifeRing,
  FaCodeBranch,
  FaBookOpen,
  FaPlug,
  FaChessRook,
  FaUser,
  FaUpload,
  FaLayerGroup,
  FaCogs,
  FaChartLine,
  FaThLarge,
  FaCheckSquare,
  FaBook,
  FaSass,
  FaRocket,
  FaShieldAlt,
  FaPaintBrush,
  FaCloud,
  FaLock,
  FaChartPie,
  FaPalette,
  FaBolt,
  FaSmile,
  FaTools,
  FaLightbulb,
  FaFeather,
  FaMagic,
} from "react-icons/fa";

import {
  FiUsers,
  FiRefreshCcw,
  FiHome,
  FiSettings,
  FiDollarSign,
  FiBarChart2,
  FiPenTool,
  FiFileText,
  FiLayers,
  FiDroplet,
  FiSmartphone,
  FiBookOpen,
} from "react-icons/fi";

import { SiRedux, SiReactrouter, SiMui } from "react-icons/si";

import { FaApple, FaAndroid, FaGamepad, FaUserAlt } from "react-icons/fa";

export const FeaturesWithIconDataOne = [
  {
    id: 1,
    icon: <FaCode />,
    title: "Quality & Clean Code",
    link: "/quality-&-clean-code",
    desc: "It’s written with well code structure as clean & commented.",
  },
  {
    id: 2,
    icon: <FaBootstrap />,
    title: "Bootstrap v5",
    link: "/",
    desc: "Built on top of awesome Bootstrap latest 5.2+ version.",
  },
  {
    id: 3,
    icon: <FaIcons />,
    title: "Handmade Icons",
    link: "/handmade-icons",
    desc: "Eye-catching and hand-crafted icons includes in design.",
  },
  {
    id: 4,
    icon: <FaDesktop />,
    title: "Pre-Built Screens",
    link: "/pre-built-screens",
    desc: "Comes with a huge collection of pre-built pages & screens.",
  },
  {
    id: 5,
    icon: <FaInfinity />,
    title: "Limitless Components",
    link: "/limitless-components",
    desc: "It’s includes 10+ components to power your application.",
  },
  {
    id: 6,
    icon: <FaMobileAlt />,
    title: "Responsive & User-Friendly",
    link: "/responsive-&-user-friendly",
    desc: "Complete responsive & user-friendly to pleasing your user.",
  },
  {
    id: 7,
    icon: <FaJs />,
    title: "No jQuery Dependency",
    link: "/no-jQuery-dependency",
    desc: "The application is built completely with javascript, free of jquery.",
  },
  {
    id: 8,
    icon: <FaHeadset />,
    title: "Premium Support",
    link: "/premium-support",
    desc: "We offer six months of free support to every customer.",
  },
  {
    id: 9,
    icon: <FaSyncAlt />,
    title: "Lifetime Updates",
    link: "/lifetime-updates",
    desc: "Every purchase entitled to free updates – for lifetime.",
  },
];

export const FeaturesWithIconDataTwo = [
  {
    id: 1,
    icon: <FaTerminal />,
    title: "CLI",
    link: "/cli",
    desc: "Thanks to dedicated CLI (Command Line Interface), building template with specific architecture is even simpler, all you have to do is choose from available options.",
  },
  {
    id: 2,
    icon: <FaReact />,
    title: "React hooks",
    link: "/react-hooks",
    desc: "We’re using only newest solutions to keep our themes up-to-date with recent trends. One of them is using React Hooks which are easy to implement.",
  },
  {
    id: 3,
    icon: <FaSearch />,
    title: "SEO friendly",
    link: "/SEOfriendly",
    desc: "Using Gatsby or Next.js with SSR support significantly affects improvement in SEO and making website more visible in Google searching results.",
  },
  {
    id: 4,
    icon: <FaLifeRing />,
    title: "Envato Elite Support",
    link: "/envato-elite-support",
    desc: "We’re group of professionals offering high-end products with friendly approach to customer service. You can count on us!",
  },
  {
    id: 5,
    icon: <FaCodeBranch />,
    title: "Monorepo support",
    link: "/monorepo-support",
    desc: "Because of using Yarn Workspaces it’s much easier to optimize project and avoid dependencies conflicts.",
  },
  {
    id: 6,
    icon: <FaBookOpen />,
    title: "Well documented",
    link: "/well-documented",
    desc: "All UI components used by Pagerland themes has full documentation and examples available on Storybook.",
  },
];

export const FeaturesWithIconDataThree = [
  {
    id: 1,
    icon: <FaCode />,
    title: "Quality & Clean Code",
    link: "/quality-clean-code",
  },
  {
    id: 2,
    icon: <FaReact />,
    title: "React-Bootstrap Framework",
    link: "/react-bootstrap",
  },
  {
    id: 3,
    icon: <FaPlug />,
    title: "20+ Additional Plugins",
    link: "/plugins",
  },
  {
    id: 4,
    icon: <FaChessRook />,
    title: "6 Types Of Icons",
    link: "/icons",
  },
  {
    id: 5,
    icon: <FaUser />,
    title: "User Pages",
    link: "/user-pages",
  },
  {
    id: 6,
    icon: <FaUpload />,
    title: "File Upload",
    link: "/file-upload",
  },
  {
    id: 7,
    icon: <FaLayerGroup />,
    title: "More UI Components",
    link: "/ui-components",
  },
  {
    id: 8,
    icon: <FaCogs />,
    title: "Easy To Customize",
    link: "/customize",
  },
  {
    id: 9,
    icon: <FaChartLine />,
    title: "3 Types Of Charts",
    link: "/charts",
  },
  {
    id: 10,
    icon: <FaThLarge />,
    title: "Ready To Widgets",
    link: "/widgets",
  },
  {
    id: 11,
    icon: <FaCheckSquare />,
    title: "Validation Forms",
    link: "/validation-forms",
  },
  {
    id: 12,
    icon: <FaBook />,
    title: "Documentation",
    link: "/documentation",
  },
];

export const FeaturesWithIconDataFour = [
  {
    id: 1,
    icon: <FiUsers />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
  {
    id: 2,
    icon: <FiRefreshCcw />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
  {
    id: 3,
    icon: <FiHome />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
  {
    id: 4,
    icon: <FiSettings />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
  {
    id: 5,
    icon: <FiDollarSign />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
  {
    id: 6,
    icon: <FiBarChart2 />,
    title: "Cross-Platform",
    desc: "Your site is not complete with only landings. Get essential inner pages using our ready demos.",
    link: "/cross-platform",
  },
];

export const FeaturesWithIconDataFive = [
  {
    id: 1,
    title: "Vectors",
    link: "#vectors",
    desc: "Use SVGs that always stay crisp and you can change the color as you go.",
    icon: <FiPenTool />,
  },
  {
    id: 2,
    title: "Forms",
    link: "#forms",
    desc: "Add forms to collect your visitors' emails directly with Mailchimp.",
    icon: <FiFileText />,
  },
  {
    id: 3,
    title: "Effects",
    link: "#effects",
    desc: "Add some fancy elements to your designs by adding interactive effects.",
    icon: <FiLayers />,
  },
  {
    id: 4,
    title: "Paste CSS",
    link: "#paste-css",
    desc: "Copy CSS from Photoshop or Sketch or even your text editor.",
    icon: <FiDroplet />,
  },
  {
    id: 5,
    title: "Responsive",
    link: "#responsive",
    desc: "Have full control over mobile layouts and breakpoints.",
    icon: <FiSmartphone />,
  },
  {
    id: 6,
    title: "Library",
    link: "#library",
    desc: "Choose from presets or create your own reusable collections.",
    icon: <FiBookOpen />,
  },
];

export const FeaturesWithIconDataSix = [
  {
    id: 1,
    title: "React",
    link: "https://react.dev",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <FaReact />,
    color: "#61dafb",
  },
  {
    id: 2,
    title: "Redux",
    link: "https://redux.js.org",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <SiRedux />,
    color: "#764abc",
  },
  {
    id: 3,
    title: "React Router Dom",
    link: "https://reactrouter.com",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <SiReactrouter />,
    color: "#ca4245",
  },
  {
    id: 4,
    title: "Bootstrap",
    link: "https://getbootstrap.com",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <FaBootstrap />,
    color: "#7952b3",
  },
  {
    id: 5,
    title: "Sass",
    link: "https://sass-lang.com",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <FaSass />,
    color: "#cc6699",
  },
  {
    id: 6,
    title: "Material UI",
    link: "https://mui.com",
    desc: "The point of using Lorem Ipsum is that it has or-less normal distribution letters, as opposed Content here.",
    icon: <SiMui />,
    color: "#007fff",
  },
];

export const FeaturesWithIconDataSeven = [
  {
    id: 1,
    title: "Fast Performance",
    link: "#",
    desc: "Optimized code ensures fast loading and smooth experience across all devices.",
    icon: <FaRocket />,
    color: "#ff6b6b",
  },
  {
    id: 2,
    title: "Secure Platform",
    link: "#",
    desc: "Built with modern security practices to protect your data and privacy.",
    icon: <FaShieldAlt />,
    color: "#4dabf7",
  },
  {
    id: 3,
    title: "Easy Customization",
    link: "#",
    desc: "Highly customizable components that adapt to your project needs.",
    icon: <FaCogs />,
    color: "#51cf66",
  },
  {
    id: 4,
    title: "Mobile Friendly",
    link: "#",
    desc: "Responsive design that works perfectly on mobile, tablet, and desktop.",
    icon: <FaMobileAlt />,
    color: "#845ef7",
  },
  {
    id: 5,
    title: "Modern Design",
    link: "#",
    desc: "Clean, minimal UI with smooth animations and elegant layouts.",
    icon: <FaPaintBrush />,
    color: "#f06595",
  },
  {
    id: 6,
    title: "Analytics Ready",
    link: "#",
    desc: "Track performance and growth with integrated analytics-ready structure.",
    icon: <FaChartLine />,
    color: "#ffa94d",
  },
];

export const FeaturesWithIconDataEight = [
  {
    id: 1,
    title: "Cloud Services",
    link: "#",
    desc: "Scalable cloud solutions designed for performance and reliability.",
    icon: <FaCloud />,
    gradient: "linear-gradient(135deg, #4facfe, #00f2fe)",
  },
  {
    id: 2,
    title: "Data Security",
    link: "#",
    desc: "Advanced security layers to protect your applications and data.",
    icon: <FaLock />,
    gradient: "linear-gradient(135deg, #fa709a, #fee140)",
  },
  {
    id: 3,
    title: "Clean Code",
    link: "#",
    desc: "Maintainable, scalable, and well-structured code standards.",
    icon: <FaCode />,
    gradient: "linear-gradient(135deg, #30cfd0, #330867)",
  },
  {
    id: 4,
    title: "UI / UX Design",
    link: "#",
    desc: "Beautiful interfaces focused on usability and user experience.",
    icon: <FaPalette />,
    gradient: "linear-gradient(135deg, #667eea, #764ba2)",
  },
  {
    id: 5,
    title: "Mobile Ready",
    link: "#",
    desc: "Fully responsive designs that adapt to every screen size.",
    icon: <FaMobileAlt />,
    gradient: "linear-gradient(135deg, #f7971e, #ffd200)",
  },
  {
    id: 6,
    title: "Analytics",
    link: "#",
    desc: "Insights-driven analytics to track growth and performance.",
    icon: <FaChartPie />,
    gradient: "linear-gradient(135deg, #43e97b, #38f9d7)",
  },
];

export const FeaturesWithIconDataNine = [
  {
    id: 1,
    title: "Lightning Speed",
    link: "#",
    desc: "Experience ultra-fast performance with optimized workflows.",
    icon: <FaBolt />,
    accent: "#ff922b",
  },
  {
    id: 2,
    title: "Layered Structure",
    link: "#",
    desc: "Well-organized architecture for scalable applications.",
    icon: <FaLayerGroup />,
    accent: "#4dabf7",
  },
  {
    id: 3,
    title: "Auto Sync",
    link: "#",
    desc: "Seamless synchronization across platforms and devices.",
    icon: <FaSyncAlt />,
    accent: "#51cf66",
  },
  {
    id: 4,
    title: "User Friendly",
    link: "#",
    desc: "Designed with simplicity and ease of use in mind.",
    icon: <FaSmile />,
    accent: "#845ef7",
  },
  {
    id: 5,
    title: "Developer Tools",
    link: "#",
    desc: "Powerful tools to speed up development and debugging.",
    icon: <FaTools />,
    accent: "#f06595",
  },
  {
    id: 6,
    title: "Smart Solutions",
    link: "#",
    desc: "Intelligent solutions built for modern business needs.",
    icon: <FaLightbulb />,
    accent: "#20c997",
  },
];

export const FeaturesWithIconDataTen = [
  {
    id: 1,
    title: "Elegant Design",
    link: "#",
    desc: "Minimal and elegant layouts crafted for modern user experiences.",
    icon: <FaFeather />,
    color: "#845ef7",
  },
  {
    id: 2,
    title: "High Performance",
    link: "#",
    desc: "Optimized architecture delivering fast and reliable performance.",
    icon: <FaBolt />,
    color: "#ff922b",
  },
  {
    id: 3,
    title: "Enterprise Security",
    link: "#",
    desc: "Advanced security practices protecting your applications.",
    icon: <FaShieldAlt />,
    color: "#4dabf7",
  },
  {
    id: 4,
    title: "Smart Automation",
    link: "#",
    desc: "Automated workflows to simplify complex operations.",
    icon: <FaMagic />,
    color: "#f06595",
  },
  {
    id: 5,
    title: "Flexible System",
    link: "#",
    desc: "Highly adaptable system that grows with your business.",
    icon: <FaCogs />,
    color: "#20c997",
  },
  {
    id: 6,
    title: "Growth Analytics",
    link: "#",
    desc: "Insightful analytics helping you track progress and growth.",
    icon: <FaChartLine />,
    color: "#51cf66",
  },
];

export const SitecoreFeaturesData = [
  {
    id: 1,
    title: "iOS App Design",
    desc: "We create smooth, innovative and best performing apps to the user requirements, for any level of complexity.",
    icon: FaApple,
    link: "/services/ios-app-design",
  },
  {
    id: 2,
    title: "Android App Design",
    desc: "With the use of the latest technologies and precise delivery of ideas.",
    icon: FaAndroid,
    link: "/services/android-app-design",
  },
  {
    id: 3,
    title: "Game App Development",
    desc: "Games are among the most prevalent apps on the app store and offer engaging experiences.",
    icon: FaGamepad,
    link: "/services/game-app-development",
  },
  {
    id: 4,
    title: "Cross-Platform App Development",
    desc: "Develop apps that work seamlessly across multiple platforms.",
    icon: FaLayerGroup,
    link: "/services/cross-platform",
  },
  {
    id: 5,
    title: "User Experience (UX) Design",
    desc: "Design intuitive experiences that keep users engaged.",
    icon: FaUserAlt,
    link: "/services/ux-design",
  },
  {
    id: 6,
    title: "User Interface (UI) Design",
    desc: "Beautiful and functional interfaces for your applications.",
    icon: FaPaintBrush,
    link: "/services/ui-design",
  },
];
